export const Chara = {
  '0': { name: '不明', color: 'gray' },

  '1': { name: '赤鬼カギコ', color: 'deeppink' },
  '2': { name: '悪亜チノン', color: 'deepskyblue' },
  '3': { name: '不死ミヨミ', color: 'gold' },
  '4': { name: 'パイン', color: 'yellow' },
  '5': { name: '首塚ツバキ', color: 'gainsboro' },
  '6': { name: '紅刃', color: 'crimson' },
  '7': { name: '首塚ボタン', color: 'orchid' },
  '8': { name: 'クルル', color: 'green' },
  '9': { name: 'ミロク', color: 'chartreuse' },
  '10': { name: '最愛チアモ', color: 'lightpink' },
  '11': { name: 'マラリヤ', color: 'purple' },
  '12': { name: 'ツバキ【廻】', color: 'indigo' },
  '13': { name: 'ジョウカ', color: 'skyblue' },
  '14': { name: 'ジャスイ', color: 'wheat' },

  // NOTE: 仮を含む
  '101': { name: '[サカサマ]カギコ', color: 'deeppink' },
  '102': { name: '[サカサマ]チノン', color: 'deepskyblue' },
  '103': { name: '[サカサマ]ミヨミ', color: 'gold' },
  '104': { name: '[サカサマ]パイン', color: 'yellow' },
  '105': { name: '[サカサマ]ツバキ', color: 'gainsboro' },
  '106': { name: '[サカサマ]紅刃', color: 'crimson' },
  '107': { name: '[サカサマ]ボタン', color: 'orchid' },
  '108': { name: '[サカサマ]クルル', color: 'green' },
  '109': { name: '[サカサマ]ミロク', color: 'chartreuse' },
  '110': { name: '[サカサマ]チアモ', color: 'lightpink' },
  '111': { name: '[サカサマ]マラリヤ', color: 'purple' },
  '112': { name: '[サカサマ]ツバキ【廻】', color: 'indigo' },
  '113': { name: '[サカサマ]ジョウカ', color: 'skyblue' },
  '114': { name: '[サカサマ]ジャスイ', color: 'wheat' },
}
