export const PrefectureAchievements = [
  { name: '北海道', achievement: 'North Sea Road' },
  { name: '青森県', achievement: 'Blue Forest' },
  { name: '岩手県', achievement: 'Rock Hand' },
  { name: '宮城県', achievement: 'Palace Castle' },
  { name: '秋田県', achievement: 'Autumn Paddy' },
  { name: '山形県', achievement: 'Mountain Form' },
  { name: '福島県', achievement: 'Happy Island' },
  { name: '茨城県', achievement: 'Thorn Castle' },
  { name: '栃木県', achievement: 'Buckeye' },
  { name: '群馬県', achievement: 'Herd Horse' },
  { name: '埼玉県', achievement: 'Cape Ball' },
  { name: '千葉県', achievement: 'Thousand Leaf' },
  { name: '東京都', achievement: 'East Capital' },
  { name: '神奈川県', achievement: 'God Apple River' },
  { name: '新潟県', achievement: 'New Lagoon' },
  { name: '富山県', achievement: 'Mt. Wealth' },
  { name: '石川県', achievement: 'Stone River' },
  { name: '福井県', achievement: 'Happy Well' },
  { name: '山梨県', achievement: 'Mountain Pear' },
  { name: '長野県', achievement: 'Long Field' },
  { name: '岐阜県', achievement: 'Crossroads Hill' },
  { name: '静岡県', achievement: 'Silent Hill' },
  { name: '愛知県', achievement: 'Love Intelligence' },
  { name: '三重県', achievement: 'Triple' },
  { name: '滋賀県', achievement: 'Moisten Celebrate' },
  { name: '京都府', achievement: 'Capital' },
  { name: '大阪府', achievement: 'Big Slope' },
  { name: '兵庫県', achievement: 'Soldier Warehouse' },
  { name: '奈良県', achievement: 'Nice Apple' },
  { name: '和歌山県', achievement: 'Mt. Gentle Song' },
  { name: '鳥取県', achievement: 'Bird Get' },
  { name: '島根県', achievement: 'Island Root' },
  { name: '岡山県', achievement: 'Mt. Hill' },
  { name: '広島県', achievement: 'Wide Island' },
  { name: '山口県', achievement: 'Mountain Mouth' },
  { name: '徳島県', achievement: 'Virtue Island' },
  { name: '香川県', achievement: 'Aroma River' },
  { name: '愛媛県', achievement: 'Love Princess' },
  { name: '高知県', achievement: 'High Intelligence' },
  { name: '福岡県', achievement: 'Happy Hill' },
  { name: '佐賀県', achievement: 'Assistant Celebrate' },
  { name: '長崎県', achievement: 'Long Cape' },
  { name: '熊本県', achievement: 'Bear Book' },
  { name: '大分県', achievement: 'Big Minute' },
  { name: '宮崎県', achievement: 'Palace Cape' },
  { name: '鹿児島県', achievement: 'Fawn Island' },
  { name: '沖縄県', achievement: 'Offing Rope' },
]
